{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-aws",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-aws-2.0.0-RELEASE.jar",
          "url": "anima-aws-2.0.0-RELEASE.jar",
          "size": 2892,
          "sha512": "b56c4b42d4ae1ddcd4339e1e0b30de608808befb6c111a0c0e9b3f270de1e228131eca05993cd63ea7a2f4c1040b735d678ec817b40f0147380c27a2d59275c3",
          "sha256": "2b5c79b83c224f36dbfe9c46762ebfb5b50cfc2ac0615bbfe40154a0a7dbe9e2",
          "sha1": "4e30a3ef8811aae26066e939e8d76bff7fe2a6a3",
          "md5": "967cd0d1b548b573fa4b7eb5c40110b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk",
          "version": {
            "requires": "1.11.201"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-secretsmanager",
          "version": {
            "requires": "1.11.320"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "4.3.12.RELEASE"
          }
        },
        {
          "group": "in.akd.anima.core",
          "module": "anima-core-logger",
          "version": {
            "requires": "2.0.0-RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "anima-aws-2.0.0-RELEASE.jar",
          "url": "anima-aws-2.0.0-RELEASE.jar",
          "size": 2892,
          "sha512": "b56c4b42d4ae1ddcd4339e1e0b30de608808befb6c111a0c0e9b3f270de1e228131eca05993cd63ea7a2f4c1040b735d678ec817b40f0147380c27a2d59275c3",
          "sha256": "2b5c79b83c224f36dbfe9c46762ebfb5b50cfc2ac0615bbfe40154a0a7dbe9e2",
          "sha1": "4e30a3ef8811aae26066e939e8d76bff7fe2a6a3",
          "md5": "967cd0d1b548b573fa4b7eb5c40110b1"
        }
      ]
    }
  ]
}
