{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-aws",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-aws-2.0.0-RELEASE.jar",
          "url": "anima-aws-2.0.0-RELEASE.jar",
          "size": 2892,
          "sha512": "29901c1c45a57ba4844185eef4d7e27d9873329d7c33f50cb9902b05c80508db9fb4adb10d753aa1b068daa1471a46a85d06389d58daef9edd8ea8a4e953c706",
          "sha256": "d251a53ae7c9578838a7e824cd319ae8f70f0da7e8a4cbe9040ae1ef75656295",
          "sha1": "55838ae415918fadb34cb957dffe641910b00f31",
          "md5": "1c1160ffe1acfb98cf0983e26f497037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk",
          "version": {
            "requires": "1.11.201"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-secretsmanager",
          "version": {
            "requires": "1.11.320"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "4.3.12.RELEASE"
          }
        },
        {
          "group": "in.akd.anima.core",
          "module": "anima-core-logger",
          "version": {
            "requires": "2.0.0-RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "anima-aws-2.0.0-RELEASE.jar",
          "url": "anima-aws-2.0.0-RELEASE.jar",
          "size": 2892,
          "sha512": "29901c1c45a57ba4844185eef4d7e27d9873329d7c33f50cb9902b05c80508db9fb4adb10d753aa1b068daa1471a46a85d06389d58daef9edd8ea8a4e953c706",
          "sha256": "d251a53ae7c9578838a7e824cd319ae8f70f0da7e8a4cbe9040ae1ef75656295",
          "sha1": "55838ae415918fadb34cb957dffe641910b00f31",
          "md5": "1c1160ffe1acfb98cf0983e26f497037"
        }
      ]
    }
  ]
}
