{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-core-logger",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-core-logger-2.0.0-RELEASE.jar",
          "url": "anima-core-logger-2.0.0-RELEASE.jar",
          "size": 3004,
          "sha512": "ad9de9a7055ba66dc68ffc6dfddd09d8b953588a5e98b8d70bcf513b86da2a023175c8168ac087326b36855d8bfeb35e1a0d84d44afab304f03e2d1514da51ad",
          "sha256": "7b09627cf56ae144f3896e3db20d70c42f96298d179892c6c075ed6b55cddb7b",
          "sha1": "186991a84296e36d3b59728799d7b9ecd80ebbbe",
          "md5": "a263107fe4d464bba15561858eef1c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-core-logger-2.0.0-RELEASE.jar",
          "url": "anima-core-logger-2.0.0-RELEASE.jar",
          "size": 3004,
          "sha512": "ad9de9a7055ba66dc68ffc6dfddd09d8b953588a5e98b8d70bcf513b86da2a023175c8168ac087326b36855d8bfeb35e1a0d84d44afab304f03e2d1514da51ad",
          "sha256": "7b09627cf56ae144f3896e3db20d70c42f96298d179892c6c075ed6b55cddb7b",
          "sha1": "186991a84296e36d3b59728799d7b9ecd80ebbbe",
          "md5": "a263107fe4d464bba15561858eef1c42"
        }
      ]
    }
  ]
}
