{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-core-logger",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-core-logger-2.0.0-RELEASE.jar",
          "url": "anima-core-logger-2.0.0-RELEASE.jar",
          "size": 3004,
          "sha512": "53c481271496a1bc00287ab5b788edec612cfc6e02190f8db230e5d2447f1f9f13b1ea24b99cd8d7035eb6f7247a7f99521fa5acf670a498a2094a4fe4295c05",
          "sha256": "8822dadc3e2fbc6b9e263bd1600ef819ef173f8f03dfae45da4dd9358013a4f7",
          "sha1": "910b6deb595dc84003d813e15bef1a1921f749bf",
          "md5": "a0d00a0c6a6f84cd316e4e4b9e9924a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-core-logger-2.0.0-RELEASE.jar",
          "url": "anima-core-logger-2.0.0-RELEASE.jar",
          "size": 3004,
          "sha512": "53c481271496a1bc00287ab5b788edec612cfc6e02190f8db230e5d2447f1f9f13b1ea24b99cd8d7035eb6f7247a7f99521fa5acf670a498a2094a4fe4295c05",
          "sha256": "8822dadc3e2fbc6b9e263bd1600ef819ef173f8f03dfae45da4dd9358013a4f7",
          "sha1": "910b6deb595dc84003d813e15bef1a1921f749bf",
          "md5": "a0d00a0c6a6f84cd316e4e4b9e9924a8"
        }
      ]
    }
  ]
}
