{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-service",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 2021,
          "sha512": "7063337ecd4ebf908937974eefd7596ecd611f00ce5a47ed5c71ec357630ccdc1c197e45893b0d50e31b7ca18604b9f15d8bf15ef30a3047b2d820cce83d3d0a",
          "sha256": "ccedcfbaad09f94d688c4269692fad1861d3fae9a48df57664efdb593bf17824",
          "sha1": "6f5a8c4379c89bbaeafa0a1d7ca14e749e524fc4",
          "md5": "d95de8f3a9cedf7cc25270d500bbdb63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "4.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.zaxxer",
              "module": "HikariCP"
            }
          ]
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.39"
          }
        }
      ],
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 2021,
          "sha512": "7063337ecd4ebf908937974eefd7596ecd611f00ce5a47ed5c71ec357630ccdc1c197e45893b0d50e31b7ca18604b9f15d8bf15ef30a3047b2d820cce83d3d0a",
          "sha256": "ccedcfbaad09f94d688c4269692fad1861d3fae9a48df57664efdb593bf17824",
          "sha1": "6f5a8c4379c89bbaeafa0a1d7ca14e749e524fc4",
          "md5": "d95de8f3a9cedf7cc25270d500bbdb63"
        }
      ]
    }
  ]
}
