{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-service",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 2021,
          "sha512": "d540cf2b717e104c264eb4f5756f0162f67101a0211280b24fffccdba45818a77a90fbb1e4a590265527dce431be53e71943012ed5590d04d45f2b623740a1ae",
          "sha256": "a141a45d3fceb87393a2609c9a2480b1f4e9236219571a7c7dd78a539064480a",
          "sha1": "0fdb6a954e636a79a414e3e326aeb067a3bac896",
          "md5": "394bde2f203c2e0e063de4ab440a145e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "4.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.zaxxer",
              "module": "HikariCP"
            }
          ]
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.39"
          }
        }
      ],
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 2021,
          "sha512": "d540cf2b717e104c264eb4f5756f0162f67101a0211280b24fffccdba45818a77a90fbb1e4a590265527dce431be53e71943012ed5590d04d45f2b623740a1ae",
          "sha256": "a141a45d3fceb87393a2609c9a2480b1f4e9236219571a7c7dd78a539064480a",
          "sha1": "0fdb6a954e636a79a414e3e326aeb067a3bac896",
          "md5": "394bde2f203c2e0e063de4ab440a145e"
        }
      ]
    }
  ]
}
