{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-service",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 7871,
          "sha512": "b8e21bf475f21d237e654fd9605ecc96a21e034b06f217814189885962096d648dc98aa759243d5a3a6fa4b2397d7a188a582f66b6b2a9e1141994af8c0ebc8a",
          "sha256": "ba277977fe120c406eecdb74d9eecf28ed45e79fc0fe67f680c017fd876d2a97",
          "sha1": "8ada474a6eaf0c848f3aedc83d739721f97702dd",
          "md5": "2ff15a59e42dadd259c466ad3792a4b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "4.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.zaxxer",
              "module": "HikariCP"
            }
          ]
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.39"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-core",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jaxb",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "io.github.openfeign.form",
          "module": "feign-form",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "anima-service-2.0.0-RELEASE.jar",
          "url": "anima-service-2.0.0-RELEASE.jar",
          "size": 7871,
          "sha512": "b8e21bf475f21d237e654fd9605ecc96a21e034b06f217814189885962096d648dc98aa759243d5a3a6fa4b2397d7a188a582f66b6b2a9e1141994af8c0ebc8a",
          "sha256": "ba277977fe120c406eecdb74d9eecf28ed45e79fc0fe67f680c017fd876d2a97",
          "sha1": "8ada474a6eaf0c848f3aedc83d739721f97702dd",
          "md5": "2ff15a59e42dadd259c466ad3792a4b0"
        }
      ]
    }
  ]
}
