{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-cache",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-cache-2.0.0-RELEASE.jar",
          "url": "anima-cache-2.0.0-RELEASE.jar",
          "size": 13878,
          "sha512": "a7da4815358e59b8608d738e693e0b89dd857e78683d2e18a271fedd52a560276d6130faaaedb77af56cdf13f140931eb78e92f3ba6dafcb908c9bddaebdde2e",
          "sha256": "2e410fe59879f7506ad18301945bd032c2c0b432b0c52ce40910e87f92c7b9cd",
          "sha1": "09a493e69f095889133c1dd07e72811c24067f9b",
          "md5": "788efb0479d6e491519e2d1a43f4efc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-cache-2.0.0-RELEASE.jar",
          "url": "anima-cache-2.0.0-RELEASE.jar",
          "size": 13878,
          "sha512": "a7da4815358e59b8608d738e693e0b89dd857e78683d2e18a271fedd52a560276d6130faaaedb77af56cdf13f140931eb78e92f3ba6dafcb908c9bddaebdde2e",
          "sha256": "2e410fe59879f7506ad18301945bd032c2c0b432b0c52ce40910e87f92c7b9cd",
          "sha1": "09a493e69f095889133c1dd07e72811c24067f9b",
          "md5": "788efb0479d6e491519e2d1a43f4efc5"
        }
      ]
    }
  ]
}
