{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-cache",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-cache-2.0.0-RELEASE.jar",
          "url": "anima-cache-2.0.0-RELEASE.jar",
          "size": 13878,
          "sha512": "b0d322ae695c33cc673039c766012a0cc7d0737b2e90394f055672a088849c95c86eb63c39846d958c893cdc80a86b5bbe4f0897f6aeaf00bc30ddb98f5416fa",
          "sha256": "1070da81075374eacfb87251dc4f04138a48380342a08bb9644a0035c0db510c",
          "sha1": "1205252a1c65311411ac63cb19b09efc2d7df602",
          "md5": "620be286156f4f3ca7f1eb4f6ce8d497"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-cache-2.0.0-RELEASE.jar",
          "url": "anima-cache-2.0.0-RELEASE.jar",
          "size": 13878,
          "sha512": "b0d322ae695c33cc673039c766012a0cc7d0737b2e90394f055672a088849c95c86eb63c39846d958c893cdc80a86b5bbe4f0897f6aeaf00bc30ddb98f5416fa",
          "sha256": "1070da81075374eacfb87251dc4f04138a48380342a08bb9644a0035c0db510c",
          "sha1": "1205252a1c65311411ac63cb19b09efc2d7df602",
          "md5": "620be286156f4f3ca7f1eb4f6ce8d497"
        }
      ]
    }
  ]
}
