{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-api",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-api-2.0.0-RELEASE.jar",
          "url": "anima-api-2.0.0-RELEASE.jar",
          "size": 261,
          "sha512": "1ce52702c397b91272c1edb6018a51570e6ef18b77b9a8af207b949c082e0fa6012d9c85c1be326e6df453474155af23131aeb7cbbf20725439a5382b22e5820",
          "sha256": "a2ccc38e27decbc6c412bf336048720cde430eed419981c337459db36396ae09",
          "sha1": "b7c1e969fd215f7c80538c9deda20d462da772d7",
          "md5": "e89871a9025ebafcac098b4ed8653473"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-api-2.0.0-RELEASE.jar",
          "url": "anima-api-2.0.0-RELEASE.jar",
          "size": 261,
          "sha512": "1ce52702c397b91272c1edb6018a51570e6ef18b77b9a8af207b949c082e0fa6012d9c85c1be326e6df453474155af23131aeb7cbbf20725439a5382b22e5820",
          "sha256": "a2ccc38e27decbc6c412bf336048720cde430eed419981c337459db36396ae09",
          "sha1": "b7c1e969fd215f7c80538c9deda20d462da772d7",
          "md5": "e89871a9025ebafcac098b4ed8653473"
        }
      ]
    }
  ]
}
