{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-api",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-api-2.0.0-RELEASE.jar",
          "url": "anima-api-2.0.0-RELEASE.jar",
          "size": 261,
          "sha512": "56ef3be471485e578d208c39ad249ebeee4ef6158e19c734d7d0e5c22686d8ef7ac15d959d397fe96c8616f022e500974297cc68e4a4a84dc52d7ccb86c88a05",
          "sha256": "2fd7612256aea70bcc592fe490985eb97c875c6c617749851f0a74080c2459ed",
          "sha1": "2905b23972abac7402ce97ee87c6a82e5b78be93",
          "md5": "966a9d8f84527f9a167f58f0cd3b1657"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-api-2.0.0-RELEASE.jar",
          "url": "anima-api-2.0.0-RELEASE.jar",
          "size": 261,
          "sha512": "56ef3be471485e578d208c39ad249ebeee4ef6158e19c734d7d0e5c22686d8ef7ac15d959d397fe96c8616f022e500974297cc68e4a4a84dc52d7ccb86c88a05",
          "sha256": "2fd7612256aea70bcc592fe490985eb97c875c6c617749851f0a74080c2459ed",
          "sha1": "2905b23972abac7402ce97ee87c6a82e5b78be93",
          "md5": "966a9d8f84527f9a167f58f0cd3b1657"
        }
      ]
    }
  ]
}
