{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-common",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 20976,
          "sha512": "26292aa023033c299f0e6969d9b8b1c0acdf9a213a98f65c8b98360ebdff75137a53cc4a7bac4b321779cd72d64d1aa8ea30079736b7049cbfdca8a99e065e28",
          "sha256": "6fd6ee1ca7280a24ff6e6b225b79a87fae56ea158be12abee0bf144a3aa3dbe3",
          "sha1": "fe71947e1d152331d4348f6dbd6307303400348e",
          "md5": "3c5ccd327c810a51eac026ae93b65a0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 20976,
          "sha512": "26292aa023033c299f0e6969d9b8b1c0acdf9a213a98f65c8b98360ebdff75137a53cc4a7bac4b321779cd72d64d1aa8ea30079736b7049cbfdca8a99e065e28",
          "sha256": "6fd6ee1ca7280a24ff6e6b225b79a87fae56ea158be12abee0bf144a3aa3dbe3",
          "sha1": "fe71947e1d152331d4348f6dbd6307303400348e",
          "md5": "3c5ccd327c810a51eac026ae93b65a0c"
        }
      ]
    }
  ]
}
