{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-common",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 15313,
          "sha512": "aed93c68209dee2dec0fbf8c80f8b44e20bf2b377a39e95b800906ef66acaa0304f0d6b7e8196da04c24b4be95fc5aa51927d3954c43e20e3d9a1da1f25928ab",
          "sha256": "1e27cf213bbba10881238b43c995ed8ed0247f380341eb3ada9a0c5b628ff51f",
          "sha1": "d2695dfe38c38ba760c706f3cc230bdb2b347076",
          "md5": "246af19689b2e14bfc7772daba546555"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 15313,
          "sha512": "aed93c68209dee2dec0fbf8c80f8b44e20bf2b377a39e95b800906ef66acaa0304f0d6b7e8196da04c24b4be95fc5aa51927d3954c43e20e3d9a1da1f25928ab",
          "sha256": "1e27cf213bbba10881238b43c995ed8ed0247f380341eb3ada9a0c5b628ff51f",
          "sha1": "d2695dfe38c38ba760c706f3cc230bdb2b347076",
          "md5": "246af19689b2e14bfc7772daba546555"
        }
      ]
    }
  ]
}
