{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-common",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 20976,
          "sha512": "cbbaf1510d17aa122bb0e2c9d7529c3f2fe10d7a024f261558984a614210238018355f19535ba9b4e772ee5467c9253098d19b07a0bf45af8e3d57f8599e8fa6",
          "sha256": "99c917f152c61705d8b1c49e1d49084c74b11ce513e23a11655b9c4b7d104005",
          "sha1": "fd2aeda89e5fc0672789e56989f566eb110abb84",
          "md5": "b9f06cfa5fad265f4c9270d561ce0598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-common-2.0.0-RELEASE.jar",
          "url": "anima-common-2.0.0-RELEASE.jar",
          "size": 20976,
          "sha512": "cbbaf1510d17aa122bb0e2c9d7529c3f2fe10d7a024f261558984a614210238018355f19535ba9b4e772ee5467c9253098d19b07a0bf45af8e3d57f8599e8fa6",
          "sha256": "99c917f152c61705d8b1c49e1d49084c74b11ce513e23a11655b9c4b7d104005",
          "sha1": "fd2aeda89e5fc0672789e56989f566eb110abb84",
          "md5": "b9f06cfa5fad265f4c9270d561ce0598"
        }
      ]
    }
  ]
}
