{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima",
    "module": "quiz",
    "version": "1.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "quiz-1.0.0-RELEASE-plain.jar",
          "url": "quiz-1.0.0-RELEASE-plain.jar",
          "size": 65598,
          "sha512": "fabae20de87fd6f508d54313d3bf67e2d7c1005ad9342ed479af209ba09933a9acff0a2e6303ecf1f6be410c21e29938bb0b46b1b515f90b0b044f23aaeabca2",
          "sha256": "7f57754f1d890ef4138f61772f1e998985b2ab859fd92d0c71012cc3bea650c0",
          "sha1": "31a2a9f1da7e014daec298377e789346676006bf",
          "md5": "dcebb6d3f695e9fdaddb833cc40234d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.apache.tomcat",
          "module": "tomcat-jdbc",
          "version": {
            "requires": "9.0.10"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-ri",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jersey",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "2.25.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-jaxrs2",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-ui",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "io.swagger.parser.v3",
          "module": "swagger-parser-v3",
          "version": {
            "requires": "2.0.27"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mapstruct",
          "module": "mapstruct",
          "version": {
            "requires": "1.4.2.Final"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "5.2.2"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "in.akd.anima.core",
          "module": "anima-core-logger",
          "version": {
            "requires": "2.0.0-RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "in.akd.anima.core",
          "module": "anima-utility",
          "version": {
            "requires": "2.0.0-RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "in.akd.anima.core",
          "module": "anima-crud",
          "version": {
            "requires": "2.0.0-RELEASE"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.apache.maven.plugins",
          "module": "maven-compiler-plugin",
          "version": {
            "requires": "3.10.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "6.5.7"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.28"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "quiz-1.0.0-RELEASE-plain.jar",
          "url": "quiz-1.0.0-RELEASE-plain.jar",
          "size": 65598,
          "sha512": "fabae20de87fd6f508d54313d3bf67e2d7c1005ad9342ed479af209ba09933a9acff0a2e6303ecf1f6be410c21e29938bb0b46b1b515f90b0b044f23aaeabca2",
          "sha256": "7f57754f1d890ef4138f61772f1e998985b2ab859fd92d0c71012cc3bea650c0",
          "sha1": "31a2a9f1da7e014daec298377e789346676006bf",
          "md5": "dcebb6d3f695e9fdaddb833cc40234d4"
        }
      ]
    }
  ]
}
