{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-utility",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "6962c6cbb65d6d1ff6a4b844d6d641f06ab14fcce36617fb684394990c42a4a23b023e4f2f1113dc0661282bc55df70648c84eed6cb3c253ad65292b71d837ca",
          "sha256": "a3f5387ec957060220a8e37bfe75b11e387e038704ee681f3418926ce8c17872",
          "sha1": "01cccadd7d6a5b0c526e253b2ffb1fc653a9bb13",
          "md5": "81475d366e9f49e3bd5d2e6721e3ac64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "6962c6cbb65d6d1ff6a4b844d6d641f06ab14fcce36617fb684394990c42a4a23b023e4f2f1113dc0661282bc55df70648c84eed6cb3c253ad65292b71d837ca",
          "sha256": "a3f5387ec957060220a8e37bfe75b11e387e038704ee681f3418926ce8c17872",
          "sha1": "01cccadd7d6a5b0c526e253b2ffb1fc653a9bb13",
          "md5": "81475d366e9f49e3bd5d2e6721e3ac64"
        }
      ]
    }
  ]
}
