{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-utility",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "ea1351b2f87d5f977a38ce21856a614ff0aff5c31ab00e63b4e1d0b8d7f8a58a6e859dadfcc33b12a11218605bcbe5d19e4b20e6834db0daf5a3b45cac42c940",
          "sha256": "e43b777cb8cf8e48f69b2a335d128012893fcf1097540b4c61ce61a8e561f3c4",
          "sha1": "338081dad0aa1a665057aec22125131419b164cc",
          "md5": "d68937385058659e3b46e16c91a1ce16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "ea1351b2f87d5f977a38ce21856a614ff0aff5c31ab00e63b4e1d0b8d7f8a58a6e859dadfcc33b12a11218605bcbe5d19e4b20e6834db0daf5a3b45cac42c940",
          "sha256": "e43b777cb8cf8e48f69b2a335d128012893fcf1097540b4c61ce61a8e561f3c4",
          "sha1": "338081dad0aa1a665057aec22125131419b164cc",
          "md5": "d68937385058659e3b46e16c91a1ce16"
        }
      ]
    }
  ]
}
