{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-utility",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "207583761f76cb0176e29bf8577537a376403fcde83648d3b7a482234faf1969c60b63f1478c9b9287934c3a8c81a819ced877260c48be918abc4a89709795f0",
          "sha256": "7d94ad2087e938f98fd5b4c9d99592ff1fc2485f200cf0e05f6a3d946b92e193",
          "sha1": "2247b99bc8e8d770d9e2edef6acdfe559e8bcc34",
          "md5": "b667fd92462bac5ef11b50ca00b52ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anima-utility-2.0.0-RELEASE.jar",
          "url": "anima-utility-2.0.0-RELEASE.jar",
          "size": 3311,
          "sha512": "207583761f76cb0176e29bf8577537a376403fcde83648d3b7a482234faf1969c60b63f1478c9b9287934c3a8c81a819ced877260c48be918abc4a89709795f0",
          "sha256": "7d94ad2087e938f98fd5b4c9d99592ff1fc2485f200cf0e05f6a3d946b92e193",
          "sha1": "2247b99bc8e8d770d9e2edef6acdfe559e8bcc34",
          "md5": "b667fd92462bac5ef11b50ca00b52ebf"
        }
      ]
    }
  ]
}
