{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-crud",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-crud-2.0.0-RELEASE.jar",
          "url": "anima-crud-2.0.0-RELEASE.jar",
          "size": 92006,
          "sha512": "4ce81564a6d098f046d13c3fe0b5cb83c083bc3de1f9e36a8aa24560164bfcddfcee58fe0226912e7051d2b1afe9a5c0d0a2347d7a5e74d16ce1d83a741bc1c2",
          "sha256": "4907b61ef6ab7dbdffb34f897489a5d610ca56f24b3545a5e58725327ef5a15a",
          "sha1": "3b5696acda703de1875934e24c1097b5c3a42eae",
          "md5": "348ced5dac0c0401ecf05e697bf343a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          },
          "excludes": [
            {
              "group": "com.zaxxer",
              "module": "HikariCP"
            }
          ]
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "anima-crud-2.0.0-RELEASE.jar",
          "url": "anima-crud-2.0.0-RELEASE.jar",
          "size": 92006,
          "sha512": "4ce81564a6d098f046d13c3fe0b5cb83c083bc3de1f9e36a8aa24560164bfcddfcee58fe0226912e7051d2b1afe9a5c0d0a2347d7a5e74d16ce1d83a741bc1c2",
          "sha256": "4907b61ef6ab7dbdffb34f897489a5d610ca56f24b3545a5e58725327ef5a15a",
          "sha1": "3b5696acda703de1875934e24c1097b5c3a42eae",
          "md5": "348ced5dac0c0401ecf05e697bf343a9"
        }
      ]
    }
  ]
}
