{
  "formatVersion": "1.1",
  "component": {
    "group": "in.akd.anima.core",
    "module": "anima-crud",
    "version": "2.0.0-RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "anima-crud-2.0.0-RELEASE.jar",
          "url": "anima-crud-2.0.0-RELEASE.jar",
          "size": 83232,
          "sha512": "49db274796af1f2e40ec7bbfaa8b6ea71387640bece92eee558dd7c3c49bcea1b1f2dc51c8baada74e0f8909204de9a9f97ef62be3d1ed63039eaecebcf9d50a",
          "sha256": "908bbef2cce43599fdc0d21101fda6ebab001192f0a23eb3ba136f4fcc407dbc",
          "sha1": "01e3653b163fd17d173938fd50fdba2cd44f14c0",
          "md5": "c35821e2130e5667858c499193c91dbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.maven.plugins",
          "module": "maven-compiler-plugin",
          "version": {
            "requires": "3.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "anima-crud-2.0.0-RELEASE.jar",
          "url": "anima-crud-2.0.0-RELEASE.jar",
          "size": 83232,
          "sha512": "49db274796af1f2e40ec7bbfaa8b6ea71387640bece92eee558dd7c3c49bcea1b1f2dc51c8baada74e0f8909204de9a9f97ef62be3d1ed63039eaecebcf9d50a",
          "sha256": "908bbef2cce43599fdc0d21101fda6ebab001192f0a23eb3ba136f4fcc407dbc",
          "sha1": "01e3653b163fd17d173938fd50fdba2cd44f14c0",
          "md5": "c35821e2130e5667858c499193c91dbb"
        }
      ]
    }
  ]
}
